version: '3'

services:
  db:
    image: postgres
    container_name: webhooket-db
    env_file:
      - ./docker.env
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 btray.main:application --log-file -
    container_name: webhooket
    volumes:
      - .:/var/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./docker.env
    environment:
      - FLASK_DEBUG=1
